# Generated by Django 3.0.7 on 2020-07-26 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='notes/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('author', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='default.jpg', upload_to='media/profile_pics')),
                ('stream', models.CharField(choices=[('Humanities', 'Humanities'), ('Commerce', 'Commerce'), ('Engineering', 'Engineering'), ('Medical', 'Medical')], default='Engineering', max_length=15)),
                ('college', models.CharField(default='', max_length=100)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
