# Generated by Django 3.0.7 on 2020-07-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stream',
            field=models.CharField(choices=[('Humanities', 'Humanities'), ('Medical', 'Medical'), ('Engineering', 'Engineering'), ('Commerce', 'Commerce')], default='Engineering', max_length=15),
        ),
    ]
