# Generated by Django 3.0.7 on 2020-07-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20200726_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stream',
            field=models.CharField(choices=[('Humanities', 'Humanities'), ('Engineering', 'Engineering'), ('Medical', 'Medical'), ('Commerce', 'Commerce')], default='Engineering', max_length=15),
        ),
    ]
