# Generated by Django 3.0.7 on 2020-07-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20200726_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='stream',
            field=models.CharField(choices=[('Commerce', 'Commerce'), ('Medical', 'Medical'), ('Humanities', 'Humanities'), ('Engineering', 'Engineering')], default='Engineering', max_length=15),
        ),
    ]
