# Generated by Django 3.1 on 2020-08-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20200726_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='../media/profile_pics'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stream',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Humanities', 'Humanities'), ('Commerce', 'Commerce'), ('Medical', 'Medical')], default='Engineering', max_length=15),
        ),
    ]
